import React from 'react'
import ReactDOM from 'react-dom'
import renderer from 'react-test-renderer'
import ErrorBoundary from './ErrorBoundary'
import Enzyme from 'enzyme'
import Adapter from 'enzyme-adapter-react-16'
import sinon from 'sinon'
import { mount, shallow } from 'enzyme'

function ProblemChild() {
    throw new Error('Error thrown from problem child');
    return <div>Error</div>; // eslint-disable-line
  }
  
  it('displays error message on error generated by child', () => {
    const wrapper = shallow(
      <ErrorBoundary > 
        <ProblemChild />
      </ErrorBoundary> 
    );
    wrapper.setState({ hasError: true });
  });