import React from 'react'
import ErrorBoundary from './ErrorBoundary'
import { shallow } from 'enzyme'


function ProblemChild() {
    throw new Error('Error thrown from problem child');
    return <div>Error</div>; // eslint-disable-line
  }
  
  it('displays error message on error generated by child', () => {
    const wrapper = shallow(
      <ErrorBoundary > 
        <ProblemChild />
      </ErrorBoundary> 
    );
    wrapper.setState({ hasError: true });
  });